### ISSUE TITLE
New columns to be added in the reports

### ISSUE THREAD

**Issue by vindeolal** [avniproject/jss-sickle-cell-screening#50]
**Context**
We have added a new question "Type of person screened" in the reg form and have migrated data from "Weather registration for pregnant women". 
Right now all the reports only use  "Weather registration for pregnant women" to find out ANC/Non-ANC cases but now there are more cases so we need to add all those in the reports.

Reports list(Only use the first sheet "Add new columns"): https://docs.google.com/spreadsheets/d/1uaZpVW9UvUw8gmSh9AJHPWtD56yljrU7d94ktXab3Hc/edit#gid=1074500827

**Comment by sachsk** [comment]
putting it on hold as saahas work needs to be pick up

**Comment by sachsk** [comment]
fixed Count all ANC/Non-ANC report.
Picking another high-priority task. so moving on hold

**Comment by garimadosar5** [comment]
**QA Notes -**
- Row 4. Report is still showing 0 result. **It's not fixed**
-  Row 5. In the column - Type of Patient only Other type is showing. other rows are blank. **It showing first 2000 individual it report has more than 50k rows so other patient data showing first**
- Row - 7. solubility +ve and solubility -ve total should be equal to total enrolment but it is less.
- Row 7. ll the genotype total should match with total enrolment. but it is not matching.
- Row 9. ANC, ANC+ve, ANC-ve, Due ANC. these columns cannot be empty.
- Reports Sample pending for electrophoresis and HPLC are giving error: question is taking too long.
- What changes are done for row 13?
